"""
fxlms.py - Filtered-X Least Mean Squares (FxLMS) ANC Engine for PS52_DANC

Implements classical normalized adaptive Filtered-X LMS (FxLMS) algorithm with:
- Configurable adaptive FIR filter length (L)
- Secondary-path electro-acoustic transfer function model S_hat(z)
- Normalized LMS weight update with leakage factor gamma
- State control: reset(), freeze_adaptation(), resume_adaptation(), set_step_size()

Signal Relationship:
--------------------
  x(n) : Reference microphone noise signal
  w(n) : Adaptive FIR controller weights [L x 1]
  y(n) : Anti-noise output generated by filter = w(n)^T * x_vec(n)
  S(z) : Secondary path (DAC -> Amp -> Speaker -> Cavity -> Error Mic)
  e(n) : Error microphone signal = d(n) - S(z)*y(n)
  x'(n): Filtered reference signal = S_hat(z) * x(n)
  
Weight Update Rule (Normalized FxLMS with Leakage):
  w(n+1) = (1 - gamma * mu) * w(n) + [ mu / (||x'||^2 + eps) ] * e(n) * x'_vec(n)

DISCLAIMER:
-----------
Secondary path model S_hat(z) is a SIMULATED synthetic FIR transfer function
for software prototype evaluation. A measured physical headset response will
replace this model during hardware integration.
"""

from typing import Tuple, Optional, Union
import numpy as np

def create_default_secondary_path(order: int = 32, delay_samples: int = 2) -> np.ndarray:
    """
    Creates a stable synthetic secondary-path FIR impulse response modeling:
    DAC -> Amplifier -> Speaker -> Cavity -> Error Microphone.
    Includes a small propagation delay and damped acoustic resonance.
    """
    t = np.arange(order, dtype=np.float32)
    # Bandpass acoustic impulse response with exponential decay
    decay = np.exp(-0.15 * t)
    resonance = np.sin(2 * np.pi * 0.12 * (t - delay_samples))
    s_path = decay * resonance
    s_path[:delay_samples] = 0.0  # Physical delay
    
    # Normalize peak energy
    norm = np.sqrt(np.sum(s_path**2))
    if norm > 0:
        s_path = s_path / norm
    return s_path.astype(np.float32)

class FxLMSFilter:
    """
    Normalized Filtered-X Least Mean Squares (FxLMS) Adaptive Filter.
    """
    def __init__(
        self,
        filter_length: int = 128,
        step_size: float = 0.005,
        leakage: float = 0.0001,
        sec_path_weights: Optional[np.ndarray] = None,
        normalized: bool = True,
        eps: float = 1e-6
    ):
        self.filter_length = int(filter_length)
        self.step_size_mu = float(step_size)
        self.initial_mu = float(step_size)
        self.leakage_gamma = float(leakage)
        self.normalized = bool(normalized)
        self.eps = float(eps)
        
        # Secondary path estimation model S_hat(z)
        if sec_path_weights is None:
            self.sec_path = create_default_secondary_path(order=32, delay_samples=2)
        else:
            self.sec_path = np.array(sec_path_weights, dtype=np.float32)
            
        self.sec_path_len = len(self.sec_path)
        
        # Adaptive filter weights W(z)
        self.weights = np.zeros(self.filter_length, dtype=np.float32)
        
        # Internal state buffers
        self.x_buf = np.zeros(self.filter_length, dtype=np.float32)
        self.x_prime_buf = np.zeros(self.filter_length, dtype=np.float32)
        self.sec_path_input_buf = np.zeros(self.sec_path_len, dtype=np.float32)
        self.sec_path_y_buf = np.zeros(self.sec_path_len, dtype=np.float32)
        
        # State control flag
        self.adaptation_enabled = True

    def reset(self) -> None:
        """Resets filter weights and all internal state buffers to zeros."""
        self.weights.fill(0.0)
        self.x_buf.fill(0.0)
        self.x_prime_buf.fill(0.0)
        self.sec_path_input_buf.fill(0.0)
        self.sec_path_y_buf.fill(0.0)
        self.step_size_mu = self.initial_mu
        self.adaptation_enabled = True

    def freeze_adaptation(self) -> None:
        """Freezes weight adaptation updates (filter continues generating anti-noise)."""
        self.adaptation_enabled = False

    def resume_adaptation(self) -> None:
        """Resumes weight adaptation updates."""
        self.adaptation_enabled = True

    def set_step_size(self, new_mu: float) -> None:
        """Dynamically adjusts the adaptation step size mu."""
        self.step_size_mu = max(0.0, float(new_mu))

    def get_weights(self) -> np.ndarray:
        """Returns a copy of current adaptive filter weights."""
        return np.copy(self.weights)

    def process_sample(
        self,
        ref_sample: float,
        desired_sample: float,
        effective_mu: Optional[float] = None
    ) -> Tuple[float, float, float]:
        """
        Processes a single time sample n:
        1. Shift ref_sample into reference buffer x_buf.
        2. Compute anti-noise sample y(n) = w(n)^T * x_buf.
        3. Filter reference sample through secondary path model S_hat(z) -> x_prime.
        4. Pass y(n) through true secondary path model -> y_sec(n).
        5. Compute error e(n) = desired_sample - y_sec(n).
        6. Update weights w(n+1) if adaptation is enabled.
        
        Returns:
          (anti_noise_y, error_e, filtered_ref_x_prime)
        """
        # 1. Update reference buffer (newest at index 0)
        self.x_buf[1:] = self.x_buf[:-1]
        self.x_buf[0] = ref_sample
        
        # 2. Compute anti-noise output y(n)
        anti_noise_y = float(np.dot(self.weights, self.x_buf))
        
        # 3. Filter reference sample x(n) through secondary path model S_hat(z) -> x_prime(n)
        self.sec_path_input_buf[1:] = self.sec_path_input_buf[:-1]
        self.sec_path_input_buf[0] = ref_sample
        x_prime = float(np.dot(self.sec_path, self.sec_path_input_buf))
        
        self.x_prime_buf[1:] = self.x_prime_buf[:-1]
        self.x_prime_buf[0] = x_prime
        
        # 4. Pass anti-noise y(n) through secondary path to estimate acoustic arrival at error mic
        self.sec_path_y_buf[1:] = self.sec_path_y_buf[:-1]
        self.sec_path_y_buf[0] = anti_noise_y
        y_at_error_mic = float(np.dot(self.sec_path, self.sec_path_y_buf))
        
        # 5. Calculate residual error signal e(n)
        error_e = desired_sample - y_at_error_mic
        
        # 6. Adaptation Weight Update
        mu = effective_mu if effective_mu is not None else self.step_size_mu
        
        if self.adaptation_enabled and mu > 0.0:
            if self.normalized:
                norm_factor = float(np.dot(self.x_prime_buf, self.x_prime_buf)) + self.eps
                step = (mu / norm_factor) * error_e * self.x_prime_buf
            else:
                step = mu * error_e * self.x_prime_buf
                
            # Normalized LMS update with leakage
            self.weights = (1.0 - self.leakage_gamma * mu) * self.weights + step
            
        return anti_noise_y, error_e, x_prime

    def process_buffer(
        self,
        ref_signal: np.ndarray,
        desired_signal: np.ndarray,
        step_size_multipliers: Optional[np.ndarray] = None
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Processes 1D audio buffers of reference and desired signals.
        Fast inlined buffer processing with zero array reallocations.
        
        Returns:
          (anti_noise_array, error_array, filtered_ref_array)
        """
        n_samples = len(ref_signal)
        if len(desired_signal) != n_samples:
            raise ValueError("Reference and desired signals must have equal length.")
            
        y_out = np.zeros(n_samples, dtype=np.float32)
        e_out = np.zeros(n_samples, dtype=np.float32)
        x_prime_out = np.zeros(n_samples, dtype=np.float32)

        # Local variable caching for fast CPython loop
        x_buf = self.x_buf
        x_prime_buf = self.x_prime_buf
        sec_in_buf = self.sec_path_input_buf
        sec_y_buf = self.sec_path_y_buf
        sec_path = self.sec_path
        weights = self.weights
        base_mu = self.step_size_mu
        leakage = self.leakage_gamma
        eps = self.eps
        normalized = self.normalized
        adapt = self.adaptation_enabled

        for i in range(n_samples):
            ref_s = float(ref_signal[i])
            des_s = float(desired_signal[i])

            # 1. Shift reference buffer
            x_buf[1:] = x_buf[:-1]
            x_buf[0] = ref_s
            anti_noise_y = float(np.dot(weights, x_buf))

            # 2. Filter reference through secondary path -> x_prime
            sec_in_buf[1:] = sec_in_buf[:-1]
            sec_in_buf[0] = ref_s
            x_prime = float(np.dot(sec_path, sec_in_buf))

            x_prime_buf[1:] = x_prime_buf[:-1]
            x_prime_buf[0] = x_prime

            # 3. Filter anti-noise through secondary path
            sec_y_buf[1:] = sec_y_buf[:-1]
            sec_y_buf[0] = anti_noise_y
            y_at_error = float(np.dot(sec_path, sec_y_buf))

            # 4. Error signal
            error_e = des_s - y_at_error

            # 5. Weight update
            if adapt:
                mu_mult = float(step_size_multipliers[i]) if step_size_multipliers is not None else 1.0
                eff_mu = base_mu * mu_mult
                if eff_mu > 0.0:
                    if normalized:
                        norm_factor = float(np.dot(x_prime_buf, x_prime_buf)) + eps
                        step = (eff_mu / norm_factor) * error_e * x_prime_buf
                    else:
                        step = eff_mu * error_e * x_prime_buf
                    weights = (1.0 - leakage * eff_mu) * weights + step

            y_out[i] = anti_noise_y
            e_out[i] = error_e
            x_prime_out[i] = x_prime

        self.weights = weights
        return y_out, e_out, x_prime_out
